### ISSUE TITLE
build-essential is broken on Amazon AMI because of seven-zip dependency

### ISSUE THREAD

**Issue by clshrock** [chef-cookbooks/build-essential#102]
It started when windows support was added in https://github.com/chef-cookbooks/build-essential/commit/d87b036ac7015e42ba9fd5711d8f001b0b1a7739  

Amazon AMI Linux
Chef Client, version 12.3.0

why was a hard depend used when it is only applicable for 1/14 supports?

**Comment by tas50** [comment]
What about the seven-zip breaks due to the seven_zip cookbook?  For windows or any other platform to work they need their full dependencies specified in the metadata.  Without this chef-client won't converge.

**Comment by clshrock** [comment]
Fair enough.  I guess my beef is with Chef then.  I hate pulling in tons of Windows-only cookbooks on non-windows machines just because windows wants to use build-essential.
