### ISSUE TITLE
 NoMethodError: undefined method `match'

### ISSUE THREAD

**Issue by abhishekkumarsingh1** [chef-cookbooks/build-essential#113]
### Cookbook version
[Version of the cookbook where you are encountering the issue]

6.0.0

### Chef-client version
[Version of chef-client in your environment]
12.0.3
### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
CentOs6.5
### Scenario:
[What you are trying to achieve and you can't?]

Trying to use build-essential cookbook in python cookbook but chef-client dies with the following error

'Recipe: build-essential::default
  * build_essential[install_packages] action install
    * yum_package[["autoconf", "bison", "flex", "gcc", "gcc-c++", "gettext", "kernel-devel", "make", "m4", "ncurses-devel", "patch"]] action install

      ================================================================================
      Error executing action `install` on resource 'yum_package[["autoconf", "bison", "flex", "gcc", "gcc-c++", "gettext", "kernel-devel", "make", "m4", "ncurses-devel", "patch"]]'
      ================================================================================

      NoMethodError
      -------------
      undefined method `match' for #<Array:0x000000045c35b0>

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:125:in `compile_and_converge_action'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/build-essential/resources/build_essential.rb

       30:     package %w( autoconf bison flex gcc gcc-c++ gettext kernel-devel make m4 ncurses-devel patch )
       31:

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/build-essential/resources/build_essential.rb:30:in `block in class_from_file'

      yum_package("["autoconf", "bison", "flex", "gcc", "gcc-c++", "gettext", "kernel-devel", "make", "m4", "ncurses-devel", "patch"]") do
        action :install
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        package_name ["autoconf", "bison", "flex", "gcc", "gcc-c++", "gettext", "kernel-devel", "make", "m4", "ncurses-devel", "patch"]
        timeout 900
        flush_cache {:before=>false, :after=>false}
        declared_type :package
        cookbook_name "build-essential"
      end

    ================================================================================
    Error executing action `install` on resource 'build_essential[install_packages]'
    ================================================================================

    NoMethodError
    -------------
    yum_package[["autoconf", "bison", "flex", "gcc", "gcc-c++", "gettext", "kernel-devel", "make", "m4", "ncurses-devel", "patch"]] (/var/chef/cache/cookbooks/build-essential/resources/build_essential.rb line 30) had an error: NoMethodError: undefined method `match' for #<Array:0x000000045c35b0>

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:125:in `compile_and_converge_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/build-essential/recipes/default.rb

     22: build_essential 'install_packages' do
     23:   compile_time node['build-essential']['compile_time']
     24: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/build-essential/recipes/default.rb:22:in `from_file'

    build_essential_build_essential("install_packages") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :build_essential
      cookbook_name "build-essential"
      recipe_name "default"
    end

Running handlers:
[2016-07-19T16:36:28+05:30] ERROR: Running exception handlers
Running handlers complete
[2016-07-19T16:36:28+05:30] ERROR: Exception handlers complete
[2016-07-19T16:36:28+05:30] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 6.956234746 seconds
[2016-07-19T16:36:29+05:30] ERROR: build_essential[install_packages] (build-essential::default line 22) had an error: NoMethodError: yum_package[["autoconf", "bison", "flex", "gcc", "gcc-c++", "gettext", "kernel-devel", "make", "m4", "ncurses-devel", "patch"]] (/var/chef/cache/cookbooks/build-essential/resources/build_essential.rb line 30) had an error: NoMethodError: undefined method `match' for #<Array:0x000000045c35b0>
[2016-07-19T16:36:29+05:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)'

changed resources/build_essential.rb

from: 
 when 'fedora', 'rhel'
   package %w( autoconf bison flex gcc gcc-c++ gettext kernel-devel make m4 ncurses-devel patch )

to 

when 'fedora', 'rhel'
    %w{ autoconf bison flex gcc gcc-c++ gettext kernel-devel make m4 ncurses-devel patch }.each do |pkg|
      package pkg
    end

fixed the issue.

**Comment by tas50** [comment]
@abhishekkumarsingh1 It looks like this cookbook actually required Chef 12.1 since it's trying to pass an array of packages to install. I forgot we introduced that in 12.1. In all honesty there aren't a lot of users running 12.0.3, as it had a few nasty regressions. I'll update the readme, and you should seriously consider upgrading to a more recently 12.X release. There's a huge number of improvements and bugfixes.
