### ISSUE TITLE
mysql_client wrong version (hardcoded ?)

### ISSUE THREAD

**Issue by skircr** [chef-cookbooks/build-essential#119]
### Cookbook version
wordpress (3.0.0)
 xml (2.0.0)
    build-essential (>= 0.0.0)
    chef-sugar (>= 0.0.0)

### Chef-client version
[Version of chef-client in your environment]

### Platform Details
Windows -> Test Kitchen -> Ubuntu 14.04

### Scenario:
Execute wordpress cookbook.

### Steps to Reproduce:
Try to execute WordPress cookbook on Ubuntu 14via TestKitchen

### Expected Result:
Live TestKitchen

### Actual Result:
...
...
 Recipe: wordpress::database
   * mysql_client_installation_package[default] action create
     * apt_package[mysql-client-5.5] action install (up to date)
      (up to date)
   * mysql2_chef_gem[default] action install
   Recipe: build-essential::_debian
     * apt_package[autoconf] action install (up to date)
     * apt_package[binutils-doc] action install (up to date)
     * apt_package[bison] action install (up to date)
     * apt_package[build-essential] action install (up to date)
     * apt_package[flex] action install (up to date)
     * apt_package[gettext] action install (up to date)
     * apt_package[ncurses-dev] action install (up to date)
     * mysql_client_installation_package[default] action create
       * apt_package[mysql-client-5.5] action install

  ================================================================================
  Error executing action `install` on resource 'apt_package[mysql-client-5.5]'
  ================================================================================

  Mixlib::ShellOut::ShellCommandFailed
  ------------------------------------
  Expected process to exit with [0], but received '100'
  ---- Begin output of apt-get -q -y install mysql-client-5.5=5.5.49-0ubuntu0.14.04.1 ----
  STDOUT: Reading package lists...
  Building dependency tree...
  Reading state information...
  STDERR: E: Version '5.5.49-0ubuntu0.14.04.1' for 'mysql-client-5.5' was not found
  ---- End output of apt-get -q -y install mysql-client-5.5=5.5.49-0ubuntu0.14.04.1 ----
  Ran apt-get -q -y install mysql-client-5.5=5.5.49-0ubuntu0.14.04.1 returned 100

**Comment by tas50** [comment]
This is actually a bug in mysql not the build-essential cookbook. You'll want to file it there
