### ISSUE TITLE
Does not install command line tools on macOS Sierra

### ISSUE THREAD

**Issue by misheska** [chef-cookbooks/build-essential#125]
### Cookbook version

7.0.1
### Chef-client version

12.15.19
### Platform Details

macOS Sierra 10.12.1 (16B2555)
### Scenario:

Command line tools are not installed on macOS Sierra

It appears that the `-v` command is no longer legal for the `softwareupdate` command:
https://github.com/chef-cookbooks/build-essential/blob/master/resources/xcode_command_line_tools.rb#L37

The most backwards-compatible way to install that would also work on macOS Sierra would be:
`softwareupdate -i "$PROD" --verbose`
### Steps to Reproduce:

Run `build-essentials` on macOS Sierra
### Expected Result:

When I run `git` or any command line tool, I should not be prompted to install the
command line tools.
### Actual Result:

I am prompted to install the command line tools.

**Comment by iennae** [comment]
Thanks for filing this. The latest cookbook resolves this problem.
