### ISSUE TITLE
chef-client 13 changes platform_family for amazon linux instances

### ISSUE THREAD

**Issue by Stromweld** [chef-cookbooks/build-essential#129]
### Cookbook version
8.0.0

### Chef-client version
13.0.118

### Platform Details
2017.03 Amazon Linux in AWS Cloud

### Scenario:
install build essential tools on amazon linux instances

### Steps to Reproduce:
create amazon linux instance with latest chef-client and build-essential cookbook in it's runlist.

### Expected Result:
gcc, make, etc... packages being installed

### Actual Result:
platform_family case statements don't have 'amazon' in their cases and thus skips over everything and moves on to the next cookbook.

**Comment by tas50** [comment]
Released in 8.0.1
