### ISSUE TITLE
Wrong version of Xcode Command Line tools is installed on High Sierra.

### ISSUE THREAD

**Issue by ryanmoon** [chef-cookbooks/build-essential#134]
### Cookbook version
8.0.4

### Chef-client version
13.6.4

### Platform Details
macOS 10.13

### Scenario:
When including the build-essential cookbook in a node runlist, on a machine running 10.3.0 or higher, Command Line Tools (macOS El Capitan version 10.11) for Xcode-8.2 is installed instead of the correct version Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.2

### Steps to Reproduce:
Include build-essential in a 10.13 node's runlist. Or on a 10.13 machine without the xcode-command line tools installed on, run the following commands:
- `touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress`
- `softwareupdate -l | grep "\*.*Command Line" | head -n 1 | awk -F"*" '{print $2}' | sed -e 's/^ *//'`

You will receive:
Command Line Tools (macOS El Capitan version 10.11) for Xcode-8.2

### Expected Result:
The expectation is that Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.2 would be installed.

### Actual Result:
Command Line Tools (macOS El Capitan version 10.11) for Xcode-8.2 is installed instead.

### Potential fix

Change the PROD softwareupdate command to:
`softwareupdate -l | grep "\*.*Command Line" | grep "$(sw_vers -productVersion | awk -F "." '{print $2}')" | awk -F"*" '{print $2}' | sed -e 's/^ *//' | tr -d '\n'` or something much more clever.

**Comment by tas50** [comment]
This should be fixed by just tailing the results so we pick the last not the first. I released it in 8.1.1. If this still doesn't work there's a gem for installing xcode that's probably a better idea.
