### ISSUE TITLE
Remove 'suggests' from metadata

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/build-essential#61]
Recently a PR for foodcritic [was merged](https://github.com/acrmp/foodcritic/pull/309), which will trigger a finding, as the `suggests` keyword is unimplemented in chef and related tooling.

We should remove it from this cookbook's metadata to avoid triggering the warning in the future, and ensure the README is updated with additional cookbooks that may be useful for this one.

**Comment by tas50** [comment]
#93 Fixes this
