### ISSUE TITLE
Ensure bsdutils package installed

### ISSUE THREAD

**Issue by mrjcleaver** [chef-cookbooks/build-essential#70]
Seems that post installs on debian need `logger` command that comes with this, but the package is not on at least one base image that I use

**Comment by tas50** [comment]
Do you have an example of the failure that happens without this package installed?

**Comment by tas50** [comment]
@mrjcleaver  Closing this due to lack of response. If you can give me a more detailed reasoning for this change I'd be happy to further investigate. Just open this issue back up.
