### ISSUE TITLE
new mingw toolchain causing chef 11.10.4 on AWS opsworks to error out with compile-time error

### ISSUE THREAD

**Issue by djcp** [chef-cookbooks/build-essential#84]
Spinning up ec2 instances managed by chef on opsworks are now failing here:

I'm not sure what requires this cookbook (something in the aws opsworks cookbooks?) but this is a pretty big problem for us right now.  I'm going to submit a ticket to AWS support as well.

```
================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/build-essential/providers/msys_archive.rb
================================================================================
 
 
NoMethodError
-------------
undefined method `provides' for #<Class:0x007f44d7d50778>
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/build-essential/providers/msys_archive.rb:22:in `class_from_file'
 
 
Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/build-essential/providers/msys_archive.rb:
 
15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
16:  # See the License for the specific language governing permissions and
17:  # limitations under the License.
18:  #
19:  
20:  use_inline_resources
21:  
22>> provides :msys_archive
23:  
24:  action :unpack do
25:    directory msys_dir do
26:      action :create
27:    end
28:  
29:    directory "dir-#{mingw_dir}" do
30:      action :create
31:      path mingw_dir
```

**Comment by djcp** [comment]
I traced this down to the `awscli` cookbook, which requires `python` which then requires any version of `build-essential`. Ugh.

**Comment by morrissimo** [comment]
Experiencing the same issue. It looks like the new code is using Chef 12+ syntax.

**Comment by djcp** [comment]
The simplest fix I've found so far is to define build-essentials 2.2.4 as a dependency, which then satisfies `python`'s build-essential dependency with the last chef 11 compatible release.

**Comment by morrissimo** [comment]
Yep - don't like it, but this is also not the first time we've had to do it :/

**Comment by dankuna** [comment]
+1 Seeing the same issue.

**Comment by thinkski** [comment]
+1

**Comment by drenalin23** [comment]
This also causes issues using the Ubuntu standard chef-11.8.2-2 package.

**Comment by kjhangiani** [comment]
Also experiencing the same issue, can't even spin up an instance.  Is there a workaround?  I appear to be hitting this bug before any of my custom cookbooks are even processed.

**Comment by drenalin23** [comment]
As mentioned earlier a temporary solution (or long term depending on your preference) would be to add 

cookbook 'build-essential', '2.2.4'

to your Berksfile (if you are pulling from supermarket.chef.io).

**Comment by kjhangiani** [comment]
It looks like we are pulling from https://api.berkshelf.com.  I'll try adding that to my cookbook and see if it works.

**Comment by kjhangiani** [comment]
That did work, thanks.  Will use this workaround for now (or probably forever...lol)

**Comment by OwenTuz** [comment]
This surprised us today as well - we hit on the same workaround but I've added a fix and pull request at the link above, if someone wouldn't mind taking a look.

Thanks!

**Comment by tas50** [comment]
This should be resolved in the latest release.  Sorry for the inconvenience
