### ISSUE TITLE
No longer Chef 11 compatible?

### ISSUE THREAD

**Issue by Parad0X** [chef-cookbooks/build-essential#86]
The latest version of `build-essential` is no longer Chef 11 compatible because of this commit: https://github.com/chef-cookbooks/build-essential/commit/d87b036ac7015e42ba9fd5711d8f001b0b1a7739#diff-a9095b58f2b1b9652aa1582efe01e8f1R22
`provides` is only available in Chef 12.

**Comment by tiago-cruz-movile** [comment]
This also broke the AWS OpsCode that uses Chef 11.10

**Comment by tas50** [comment]
We inadvertently broke Chef 11 compatibility with the 2.3.0 release yesterday.  This has been fixed with 2.3.1 and we've added automated integration testing on Chef 11 so our matrix so we'll catch these sort of things in the future.
