### ISSUE TITLE
why is windows transitively required 

### ISSUE THREAD

**Issue by atlasloewenherz** [chef-cookbooks/build-essential#98]
build-essential requires 7-Zip cookbooks and the latter requires windows cookbook.

is it possible for the enduser to skip this "dependency" if its not required?

unzip in debian could be an alternative option to 7zip

thanks & regards

**Comment by tas50** [comment]
7-zip is used by the windows provider which also requires the windows cookbook.  There isn't a way to avoid those dependencies, but they add probably a meg at most to your nodes during converge time and aren't executed when you're not running Windows.
